// tslint:disable-next-line: interface-name
interface Country {
  label: string;
  value: string;
}

export const countries: Country[] = [
  { label: 'Afganistán', value: 'Afganistán' },
  { label: 'Albania', value: 'Albania' },
  { label: 'Alemania', value: 'Alemania' },
  { label: 'Andorra', value: 'Andorra' },
  { label: 'Angola', value: 'Angola' },
  { label: 'Arabia Saudita', value: 'Arabia Saudita' },
  { label: 'Argelia', value: 'Argelia' },
  { label: 'Argentina', value: 'Argentina' },
  { label: 'Armenia', value: 'Armenia' },
  { label: 'Australia', value: 'Australia' },
  { label: 'Austria', value: 'Austria' },
  { label: 'Azerbaiyán', value: 'Azerbaiyán' },
  { label: 'Bahamas', value: 'Bahamas' },
  { label: 'Bangladés', value: 'Bangladés' },
  { label: 'Barbados', value: 'Barbados' },
  { label: 'Baréin', value: 'Baréin' },
  { label: 'Bélgica', value: 'Bélgica' },
  { label: 'Belice', value: 'Belice' },
  { label: 'Benín', value: 'Benín' },
  { label: 'Bielorrusia', value: 'Bielorrusia' },
  { label: 'Birmania/Myanmar', value: 'Birmania/Myanmar' },
  { label: 'Bolivia', value: 'Bolivia' },
  { label: 'Bosnia y Herzegovina', value: 'Bosnia y Herzegovina' },
  { label: 'Botsuana', value: 'Botsuana' },
  { label: 'Brasil', value: 'Brasil' },
  { label: 'Brunéi', value: 'Brunéi' },
  { label: 'Bulgaria', value: 'Bulgaria' },
  { label: 'Burkina Faso', value: 'Burkina Faso' },
  { label: 'Burundi', value: 'Burundi' },
  { label: 'Bután', value: 'Bután' },
  { label: 'Cabo Verde', value: 'Cabo Verde' },
  { label: 'Camboya', value: 'Camboya' },
  { label: 'Camerún', value: 'Camerún' },
  { label: 'Canadá', value: 'Canadá' },
  { label: 'Catar', value: 'Catar' },
  { label: 'Chile', value: 'Chile' },
  { label: 'China', value: 'China' },
  { label: 'Chipre', value: 'Chipre' },
  { label: 'Ciudad del Vaticano', value: 'Ciudad del Vaticano' },
  { label: 'Colombia', value: 'Colombia' },
  { label: 'Comoras', value: 'Comoras' },
  { label: 'Corea del Norte', value: 'Corea del Norte' },
  { label: 'Corea del Sur', value: 'Corea del Sur' },
  { label: 'Costa de Marfil', value: 'Costa de Marfil' },
  { label: 'Costa Rica', value: 'Costa Rica' },
  { label: 'Croacia', value: 'Croacia' },
  { label: 'Cuba', value: 'Cuba' },
  { label: 'Dinamarca', value: 'Dinamarca' },
  { label: 'Dominica', value: 'Dominica' },
  { label: 'Ecuador', value: 'Ecuador' },
  { label: 'Egipto', value: 'Egipto' },
  { label: 'El Salvador', value: 'El Salvador' },
  { label: 'Emiratos Árabes Unidos', value: 'Emiratos Árabes Unidos' },
  { label: 'Eritrea', value: 'Eritrea' },
  { label: 'Eslovaquia', value: 'Eslovaquia' },
  { label: 'Eslovenia', value: 'Eslovenia' },
  { label: 'España', value: 'España' },
  { label: 'Estados Unidos', value: 'Estados Unidos' },
  { label: 'Estonia', value: 'Estonia' },
  { label: 'Filipinas', value: 'Filipinas' },
  { label: 'Finlandia', value: 'Finlandia ' },
  { label: 'Francia', value: 'Francia' },
  { label: 'Guatemala', value: 'Guatemala' },
  { label: 'Haití', value: 'Haití' },
  { label: 'Honduras', value: 'Honduras' },
  { label: 'India', value: 'India' },
  { label: 'Indonesia', value: 'Indonesia' },
  { label: 'Irak', value: 'Irak' },
  { label: 'Islandia', value: 'Islandia' },
  { label: 'Italia', value: 'Italia' },
  { label: 'Jamaica', value: 'Jamaica' },
  { label: 'Japón', value: 'Japón' },
  { label: 'Kenia', value: 'Kenia' },
  { label: 'Luxemburgo', value: 'Luxemburgo' },
  { label: 'Malasia', value: 'Malasia' },
  { label: 'Marruecos', value: 'Marruecos' },
  { label: 'México', value: 'México' },
  { label: 'Mónaco', value: 'Mónaco' },
  { label: 'Mongolia', value: 'Mongolia' },
  { label: 'Nauru', value: 'Nauru' },
  { label: 'Nepal', value: 'Nepal' },
  { label: 'Nicaragua', value: 'Nicaragua' },
  { label: 'Nigeria', value: 'Nigeria' },
  { label: 'Noruega', value: 'Noruega' },
  { label: 'Nueva Zelanda', value: 'Nueva Zelanda' },
  { label: 'Países Bajos', value: 'Países Bajos' },
  { label: 'Pakistán', value: 'Pakistán' },
  { label: 'Panamá', value: 'Panamá' },
  { label: 'Paraguay', value: 'Paraguay' },
  { label: 'Perú', value: 'Perú' },
  { label: 'Puerto Rico', value: 'Puerto Rico' },
  { label: 'Polonia', value: 'Polonia' },
  { label: 'Portugal', value: 'Portugal' },
  { label: 'Reino Unido', value: 'Reino Unido' },
  { label: 'República Dominicana', value: 'República Dominicana' },
  { label: 'Rumanía', value: 'Rumanía' },
  { label: 'Rusia', value: 'Rusia' },
  { label: 'Suecia', value: 'Suecia' },
  { label: 'Suiza', value: 'Suiza' },
  { label: 'Tailandia', value: 'Tailandia' },
  { label: 'Turquía', value: 'Turquía' },
  { label: 'Ucrania', value: 'Ucrania' },
  { label: 'Uruguay', value: 'Uruguay' },
  { label: 'Venezuela', value: 'Venezuela' }
];
